# permissions for end users to view sinksconfigs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: sinksconfig-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: kvnts
    app.kubernetes.io/part-of: kvnts
    app.kubernetes.io/managed-by: kustomize
  name: sinksconfig-viewer-role
rules:
- apiGroups:
  - events.kvnts
  resources:
  - sinksconfigs
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - events.kvnts
  resources:
  - sinksconfigs/status
  verbs:
  - get
